### ISSUE TITLE
Unknown word (via CssSyntaxError) 

### ISSUE THREAD

**Issue by simrikservices** [proog/eleventy-plugin-purgecss#4] opened 2022-06-20 14:43 UTC
`[11ty] <css input>:538:9: Unknown word (via CssSyntaxError)
[11ty] Original error stack trace: CssSyntaxError: <css input>:538:9: Unknown word`

I am getting this error. Using `@11ty/eleventy": "^1.0.1`

**Comment by proog** [comment] 2022-06-20 15:40
Hi, can you provide a minimal reproducible example? On the face of it, this sounds like an issue with the actual CSS.

Thanks!

**Comment by proog** [comment] 2022-07-10 09:43
Unfortunately I can't reproduce the issue with the current information, so I'm closing it. Let me know if it's still relevant!

**Closed as not planned by proog** 2022-07-10 09:43 UTC
